/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.practica1_201503422;

/**
 *
 * @author freni_000
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        L2 = new javax.swing.JToggleButton();
        L1 = new javax.swing.JToggleButton();
        L3 = new javax.swing.JToggleButton();
        L6 = new javax.swing.JToggleButton();
        L5 = new javax.swing.JToggleButton();
        L7 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Jugador = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        L4 = new javax.swing.JToggleButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 34, 661, 490);

        L2.setBackground(new java.awt.Color(255, 255, 204));
        L2.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        L2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        L2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L2.setLabel("A");
        getContentPane().add(L2);
        L2.setBounds(150, 530, 59, 44);

        L1.setBackground(new java.awt.Color(255, 255, 204));
        L1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        L1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        L1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L1.setLabel("A");
        getContentPane().add(L1);
        L1.setBounds(80, 530, 59, 44);

        L3.setBackground(new java.awt.Color(255, 255, 204));
        L3.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        L3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        L3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L3.setLabel("A");
        getContentPane().add(L3);
        L3.setBounds(230, 530, 59, 44);

        L6.setBackground(new java.awt.Color(255, 255, 204));
        L6.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        L6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        L6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L6.setLabel("A");
        getContentPane().add(L6);
        L6.setBounds(460, 530, 59, 44);

        L5.setBackground(new java.awt.Color(255, 255, 204));
        L5.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        L5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        L5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L5.setLabel("A");
        getContentPane().add(L5);
        L5.setBounds(380, 530, 59, 44);

        L7.setBackground(new java.awt.Color(255, 255, 204));
        L7.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        L7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        L7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L7.setLabel("A");
        getContentPane().add(L7);
        L7.setBounds(540, 530, 59, 44);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Jugador", "Punteo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(680, 40, 170, 190);

        Jugador.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Jugador.setText("Jugador");
        getContentPane().add(Jugador);
        Jugador.setBounds(10, 0, 270, 30);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista Diccionario", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fichas Activas", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gráfica Tablero", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cola Total Fichas", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Jugadores", jPanel6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(860, 40, 270, 530);

        L4.setBackground(new java.awt.Color(255, 255, 204));
        L4.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        L4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        L4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L4.setLabel("A");
        getContentPane().add(L4);
        L4.setBounds(300, 530, 59, 44);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jugador;
    private javax.swing.JToggleButton L1;
    private javax.swing.JToggleButton L2;
    private javax.swing.JToggleButton L3;
    private javax.swing.JToggleButton L4;
    private javax.swing.JToggleButton L5;
    private javax.swing.JToggleButton L6;
    private javax.swing.JToggleButton L7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
